# Generated by Django 4.2.21 on 2025-05-14 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_host_port'),
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleddeployment',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.environment'),
        ),
    ]
