---
- name: Configuración de servidor web en Oracle Linux 9
  hosts: target_group
  become: yes
  vars:
    subdomain: "{{ target_group }}"
    deployment_timestamp: "{{ ansible_date_time.iso8601 }}"

  tasks:
    - name: Actualizar sistema operativo
      dnf:
        name: '*'
        state: latest
      register: result_update

    - name: Debug result_update
      debug:
        var: result_update

    - name: Instalar Apache (httpd)
      dnf:
        name:
          - httpd
        state: present

    - name: Asegurar que los servicios httpd y firewalld estén iniciados y habilitados
      systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - httpd
        - firewalld

    - name: Abrir puerto HTTP permanentemente en el firewall
      command: firewall-cmd --permanent --add-port={{ http_port }}/tcp
      ignore_errors: true

    - name: Abrir puerto HTTPS permanentemente en el firewall
      command: firewall-cmd --permanent --add-port={{ https_port }}/tcp
      ignore_errors: true

    - name: Recargar firewalld
      systemd:
        name: firewalld
        state: reloaded

    - name: Deshabilitar SELinux (temporalmente)
      command: setenforce 0
      ignore_errors: true

    - name: Deshabilitar SELinux permanentemente
      command: echo "SELINUX=disabled" > /etc/selinux/config
      ignore_errors: true

    - name: Crear directorios necesarios
      file:
        path: "{{ item.path }}"
        state: directory
        mode: "{{ item.mode | default(omit) }}"
      loop:
        - path: "{{ server_root }}/{{ target_group }}-{{ inventory_hostname }}"
        - path: "{{ log_root }}/{{ target_group }}-{{ inventory_hostname }}"
        - path: "/etc/httpd/conf.d"
          mode: "0755"
          
    - name: Renombrar el archivo actual httpd.conf a httpd.conf.bak
      command:
        cmd: mv /etc/httpd/conf/httpd.conf /etc/httpd/conf/httpd.conf.bak        
      args:
        creates: /etc/httpd/conf/httpd.conf.bak

    - name: Copiar el archivo httpd.conf desde la plantilla
      template:
        src: /opt/www/media/templates/httpd.conf.j2
        dest: /etc/httpd/conf/httpd.conf
        force: yes

    - name: Limpiar archivo /etc/hostname
      copy:
        content: ""
        dest: "/etc/hostname"
        force: yes

    - name: Guardar nombre de app en /etc/hostname
      lineinfile:
        path: "/etc/hostname"
        line: "{{ target_group }}-{{ inventory_hostname }}.{{ domain }}"
        
    - name: Crear archivo index.html con contenido dinámico
      copy:
        content: |
          <!DOCTYPE html>
          <html lang="es">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>{{ inventory_hostname }} - Deployment Success</title>
              <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
              <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet">
              <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;500;700&display=swap" rel="stylesheet">
              <style>
                  :root {
                      --pastel-bg: #d7e3fc;
                      --pastel-card: #f9f6f2;
                      --accent-green: #10b981;
                      --accent-red: #ef4444;
                      --text-main: #232946;
                      --text-muted: #6c7289;
                      --diaken-blue: #274167;
                  }
                  body {
                      font-family: 'Inter', sans-serif;
                      min-height: 100vh;
                      background: var(--pastel-bg);
                      color: var(--text-main);
                      display: flex;
                      align-items: center;
                      justify-content: center;
                      margin: 0;
                      padding: 1rem;
                  }
                  .deployment-card {
                      background: var(--pastel-card);
                      border-radius: 1.5rem;
                      padding: 2.5rem 2rem;
                      box-shadow: 0 8px 32px rgba(35, 41, 70, 0.08);
                      border: 1px solid #e2e2e2;
                      max-width: 420px;
                      width: 100%;
                      animation: fadeIn 0.8s;
                      position: relative;
                  }
                  @keyframes fadeIn {
                      from { opacity: 0; transform: translateY(30px);}
                      to { opacity: 1; transform: translateY(0);}
                  }
                  .success-badge {
                      background: rgba(16, 185, 129, 0.12);
                      color: var(--accent-green);
                      padding: 0.5rem 1.2rem;
                      border-radius: 2rem;
                      display: inline-flex;
                      align-items: center;
                      gap: 0.5rem;
                      font-weight: 500;
                      font-size: 1rem;
                      margin-bottom: 1.5rem;
                  }
                  .deployment-title {
                      font-size: 2.1rem;
                      font-weight: 700;
                      margin-bottom: 1.8rem;
                      color: var(--text-main);
                      word-break: break-all;
                  }
                  .info-row {
                      background: #eef2fb;
                      border-radius: 0.75rem;
                      padding: 1.1rem 1rem;
                      margin-bottom: 1.1rem;
                      display: flex;
                      align-items: center;
                      gap: 1rem;
                  }
                  .info-icon {
                      color: #a5b4fc;
                      font-size: 1.5rem;
                  }
                  .info-content {
                      flex: 1;
                  }
                  .info-label {
                      color: var(--text-muted);
                      font-size: 0.97rem;
                      margin-bottom: 0.15rem;
                  }
                  .info-value {
                      font-size: 1.1rem;
                      font-weight: 600;
                      color: var(--text-main);
                  }
                  .diaken-badge {
                      position: absolute;
                      right: 20px;
                      bottom: 18px;
                      min-width: 64px;
                      height: 26px;
                      background: #274167;
                      color: #fff;
                      display: flex;
                      align-items: center;
                      justify-content: center;
                      font-weight: 700;
                      font-size: 0.85rem;
                      border-radius: 7px;
                      letter-spacing: 1.5px;
                      box-shadow: 0 2px 8px rgba(39,65,103,0.08);
                      border: 1.5px solid #274167;
                      z-index: 2;
                      user-select: none;
                      padding: 0 12px;
                      opacity: 0.92;
                  }
              </style>
          </head>
          <body>
              <div class="deployment-card">
                  <div class="success-badge">
                      <i class="bi bi-check-circle-fill"></i>
                      Deployment Successful
                  </div>
                  <div class="deployment-title text-center">{{ target_group }}-{{ inventory_hostname }}.{{ domain }}</div>
                  <div class="info-row">
                      <span class="info-icon"><i class="bi bi-calendar-event"></i></span>
                      <div class="info-content">
                          <div class="info-label">Deployment date and time</div>
                          <div class="info-value">{{ ansible_date_time.date }} {{ ansible_date_time.time }}</div>
                      </div>
                  </div>
                  <br>
                  <div class="diaken-badge">DIAKEN</div>
              </div>
              <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
          </body>
          </html>
        dest: "{{ server_root }}/{{ target_group }}-{{ inventory_hostname }}/index.html"
        force: yes

    - name: Crear configuración de VirtualHost para Apache
      copy:
        content: |
          <VirtualHost *:{{ http_port }}>
              ServerName {{ target_group }}-{{ inventory_hostname }}.{{ domain }}
              ServerAlias {{ target_group }}-{{ inventory_hostname }}
              DocumentRoot {{ server_root }}/{{ target_group }}-{{ inventory_hostname }}
              ErrorLog {{ log_root }}/{{ target_group }}-{{ inventory_hostname }}/error.log
              CustomLog {{ log_root }}/{{ target_group }}-{{ inventory_hostname }}/access.log combined
              
              <Directory {{ server_root }}/{{ target_group }}-{{ inventory_hostname }}>
                  Options Indexes FollowSymLinks
                  AllowOverride All
                  Require all granted
              </Directory>
          </VirtualHost>
        dest: "/etc/httpd/conf.d/{{ target_group }}-{{ inventory_hostname }}.conf"
        force: yes
      register: result
      ignore_errors: true
      notify: Reiniciar Apache

    - name: Mostrar información detallada si Apache falla al reiniciar
      debug:
        var: result
      when: result is failed

    - name: Cambiar propietario y grupo de archivos y directorios
      command: chown -R apache:apache {{ server_root }}/{{ target_group }}-{{ inventory_hostname }}

    - name: Mostrar resumen al finalizar el playbook
      debug:
        msg:
          - "Resumen de la implementación:"
          - "Nombre del servidor: {{ target_group }}-{{ inventory_hostname }}.{{ domain }}"
          - "Ruta del aplicativo: {{ server_root }}/{{ target_group }}-{{ inventory_hostname }}/index.html"
          - "Logs: {{ log_root }}/{{ target_group }}-{{ inventory_hostname }}"
          - "Permisos: apache:apache para {{ server_root }}/{{ target_group }}-{{ inventory_hostname }}"
          - "Puertos: HTTP {{ http_port }}, HTTPS {{ https_port }}"
          - "Dominio: {{ domain }}"
          - "Timestamp de despliegue: {{ deployment_timestamp }}"
          - "El playbook se ha completado correctamente."

  handlers:
    - name: Reiniciar Apache
      systemd:
        name: httpd
        state: restarted
