# Generated by Django 5.0.14 on 2025-05-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybookExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playbook_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
