# Generated by Django 5.0.14 on 2025-05-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookexecution',
            name='operating_system',
            field=models.CharField(choices=[('Windows', 'Windows'), ('RedHat', 'RedHat'), ('Debian', 'Debian')], default='RedHat', max_length=10),
        ),
    ]
