# Generated by Django 5.0.14 on 2025-04-30 03:38

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuario personalizado', 'verbose_name_plural': 'Usuarios personalizados'},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='security_phrase',
            field=models.CharField(help_text='Frase secreta para verificación adicional', max_length=128, verbose_name='Frase de seguridad'),
        ),
    ]
