---
- name: Limpiar configuraciones SSL problemáticas
  hosts: target_host
  become: yes
  tasks:
    - name: Eliminar archivo BACKEND-ssl.conf si existe
      file:
        path: /etc/httpd/conf.d/BACKEND-ssl.conf
        state: absent
      tags:
        - cleanup

    - name: Buscar archivos de configuración SSL que referencian demo01
      shell: find /etc/httpd/conf.d/ -name "*-ssl.conf" -exec grep -l "demo01" {} \; 2>/dev/null || echo ""
      register: problematic_files
      changed_when: false
      tags:
        - cleanup

    - name: Mostrar archivos problemáticos encontrados
      debug:
        msg: "Archivos problemáticos encontrados: {{ problematic_files.stdout_lines }}"
      when: problematic_files.stdout != ""
      tags:
        - cleanup

    - name: Eliminar archivos de configuración SSL problemáticos
      file:
        path: "{{ item }}"
        state: absent
      with_items: "{{ problematic_files.stdout_lines }}"
      when: problematic_files.stdout != ""
      tags:
        - cleanup

    - name: Verificar configuración de Apache
      command: httpd -t
      register: apache_config_test
      changed_when: false
      ignore_errors: yes
      tags:
        - cleanup

    - name: Reiniciar Apache si la configuración es válida
      service:
        name: httpd
        state: restarted
      when: apache_config_test.rc == 0
      tags:
        - cleanup

    - name: Mostrar error de configuración si existe
      debug:
        msg: "Error en la configuración de Apache: {{ apache_config_test.stderr }}"
      when: apache_config_test.rc != 0
      tags:
        - cleanup
