---
- name: Corregir compatibilidad entre SSL y despliegue básico de Apache
  hosts: target_host
  become: yes
  tasks:
    # Fase 1: Diagnóstico
    - name: Verificar si Apache está instalado
      command: rpm -q httpd
      register: httpd_installed
      ignore_errors: yes
      changed_when: false
      tags:
        - diagnose

    - name: Verificar estado del servicio Apache
      command: systemctl status httpd
      register: httpd_status
      ignore_errors: yes
      changed_when: false
      tags:
        - diagnose

    - name: Verificar errores en la configuración de Apache
      command: httpd -t
      register: httpd_config
      ignore_errors: yes
      changed_when: false
      tags:
        - diagnose

    - name: Mostrar errores de configuración si existen
      debug:
        msg: "{{ httpd_config.stderr_lines }}"
      when: httpd_config.rc != 0
      tags:
        - diagnose

    # Fase 2: Limpieza de configuraciones problemáticas
    - name: Eliminar configuraciones SSL problemáticas
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/httpd/conf.d/{{ target_host }}-ssl.conf
        - /etc/httpd/conf.d/{{ target_host }}-redirect.conf
        - /etc/httpd/conf.d/BACKEND-ssl.conf
      tags:
        - fix

    - name: Buscar archivos de configuración SSL problemáticos
      shell: find /etc/httpd/conf.d/ -name "*-ssl.conf" -o -name "*-redirect.conf" | xargs grep -l "demo01" 2>/dev/null || echo ""
      register: problematic_files
      changed_when: false
      tags:
        - fix

    - name: Eliminar archivos de configuración SSL problemáticos
      file:
        path: "{{ item }}"
        state: absent
      with_items: "{{ problematic_files.stdout_lines }}"
      when: problematic_files.stdout != ""
      tags:
        - fix

    # Fase 3: Crear configuración básica
    - name: Crear configuración básica de VirtualHost
      template:
        src: /opt/www/media/templates/host/virtualhost.conf.j2
        dest: /etc/httpd/conf.d/{{ target_host }}.conf
        mode: '0644'
      tags:
        - fix

    # Fase 4: Verificar y reiniciar
    - name: Verificar configuración de Apache
      command: httpd -t
      register: apache_config_test
      changed_when: false
      tags:
        - fix

    - name: Reiniciar Apache si la configuración es válida
      service:
        name: httpd
        state: restarted
      when: apache_config_test.rc == 0
      tags:
        - fix
