---
- name: Corregir configuración SSL de VSFTPD
  hosts: target_host
  become: yes
  tasks:
    # Fase 0: Validación de variables
    - name: Validar variables requeridas
      debug:
        msg: "Validando variables para el host: {{ target_host }}"
      tags:
        - always

    - name: Establecer variables por defecto si no están definidas
      set_fact:
        server_root: "{{ server_root | default('/opt/www/sites') }}"
        ftp_user: "{{ ftp_user | default('ftpuser') }}"
        ssl_cert_dir: "{{ ssl_cert_dir | default('/etc/vsftpd') }}"
      tags:
        - always

    # Fase 1: Diagnóstico
    - name: Verificar si VSFTPD está instalado
      command: which vsftpd
      register: vsftpd_installed
      ignore_errors: yes
      changed_when: false
      tags:
        - diagnose

    - name: Mostrar advertencia si VSFTPD no está instalado
      debug:
        msg: "ADVERTENCIA: VSFTPD no está instalado. Por favor, instale VSFTPD primero usando el playbook Install VSFTPD Host (Optimized v1)."
      when: vsftpd_installed.rc != 0
      tags:
        - diagnose

    - name: Verificar estado del servicio VSFTPD
      service:
        name: vsftpd
        state: stopped
      when: vsftpd_installed.rc == 0
      ignore_errors: yes
      tags:
        - diagnose

    # Fase 2: Corregir certificado SSL
    - name: Eliminar certificado SSL anterior si existe
      file:
        path: "{{ ssl_cert_dir }}/vsftpd.pem"
        state: absent
      when: vsftpd_installed.rc == 0
      tags:
        - ssl

    - name: Crear directorio para certificados si no existe
      file:
        path: "{{ ssl_cert_dir }}"
        state: directory
        mode: '0755'
      when: vsftpd_installed.rc == 0
      tags:
        - ssl

    - name: Generar nuevo certificado SSL para VSFTPD
      shell: |
        openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
          -keyout {{ ssl_cert_dir }}/vsftpd.pem -out {{ ssl_cert_dir }}/vsftpd.pem \
          -subj "/C=CO/ST=Santander/L=Bucaramanga/O={{ target_host }}/CN={{ target_host }}.{{ domain | default('upb.edu.co') }}"
        chmod 600 {{ ssl_cert_dir }}/vsftpd.pem
        chown root:root {{ ssl_cert_dir }}/vsftpd.pem
      when: vsftpd_installed.rc == 0
      tags:
        - ssl

    # Fase 3: Modificar configuración VSFTPD
    - name: Hacer backup del archivo vsftpd.conf
      copy:
        src: /etc/vsftpd/vsftpd.conf
        dest: /etc/vsftpd/vsftpd.conf.bak.{{ ansible_date_time.date }}
        remote_src: yes
      when: vsftpd_installed.rc == 0
      ignore_errors: yes
      tags:
        - configure

    - name: Actualizar configuración SSL en vsftpd.conf
      lineinfile:
        path: /etc/vsftpd/vsftpd.conf
        regexp: '^ssl_enable=.*'
        line: 'ssl_enable=YES'
      when: vsftpd_installed.rc == 0
      tags:
        - configure

    - name: Asegurar que la ruta del certificado esté correcta
      lineinfile:
        path: /etc/vsftpd/vsftpd.conf
        regexp: '^rsa_cert_file=.*'
        line: 'rsa_cert_file={{ ssl_cert_dir }}/vsftpd.pem'
        insertafter: '^ssl_enable=.*'
      when: vsftpd_installed.rc == 0
      tags:
        - configure

    - name: Asegurar que la ruta de la clave esté correcta
      lineinfile:
        path: /etc/vsftpd/vsftpd.conf
        regexp: '^rsa_private_key_file=.*'
        line: 'rsa_private_key_file={{ ssl_cert_dir }}/vsftpd.pem'
        insertafter: '^rsa_cert_file=.*'
      when: vsftpd_installed.rc == 0
      tags:
        - configure

    # Fase 4: Verificar y reiniciar VSFTPD
    - name: Verificar configuración de VSFTPD
      shell: vsftpd -olisten=NO /etc/vsftpd/vsftpd.conf
      register: vsftpd_config_test
      ignore_errors: yes
      changed_when: false
      when: vsftpd_installed.rc == 0
      tags:
        - service

    - name: Mostrar errores de configuración si existen
      debug:
        msg: "{{ vsftpd_config_test.stdout_lines }}"
      when: vsftpd_installed.rc == 0 and vsftpd_config_test.rc != 0
      tags:
        - service

    - name: Reiniciar VSFTPD si la configuración es válida
      service:
        name: vsftpd
        state: restarted
        enabled: yes
      when: vsftpd_installed.rc == 0 and vsftpd_config_test.rc == 0
      tags:
        - service

    - name: Forzar reinicio de VSFTPD incluso si la verificación falló
      service:
        name: vsftpd
        state: restarted
        enabled: yes
      when: vsftpd_installed.rc == 0 and vsftpd_config_test.rc != 0
      ignore_errors: yes
      tags:
        - service

    # Fase 5: Verificar estado final
    - name: Verificar estado del servicio VSFTPD
      shell: systemctl status vsftpd
      register: vsftpd_status
      ignore_errors: yes
      changed_when: false
      when: vsftpd_installed.rc == 0
      tags:
        - service

    - name: Mostrar estado del servicio
      debug:
        msg: "{{ vsftpd_status.stdout_lines }}"
      when: vsftpd_installed.rc == 0
      tags:
        - service

    # Fase 6: Resumen final
    - name: Mensaje de confirmación
      debug:
        msg: |
          Corrección de configuración SSL de VSFTPD completada:
          - Host: {{ target_host }}
          - Certificado SSL: {{ ssl_cert_dir }}/vsftpd.pem
          - Estado de la configuración: {{ 'Válida' if vsftpd_config_test.rc == 0 else 'Con errores, pero se intentó reiniciar el servicio' }}
          
          Para probar la conexión FTP, use un cliente FTP con soporte SSL/TLS como FileZilla.
          Usuario: {{ ftp_user }}
          Directorio: {{ server_root }}/{{ target_host }}
      tags:
        - always
