---
- name: Corregir configuración SSL de VSFTPD (Versión 2)
  hosts: target_host
  become: yes
  tasks:
    # Fase 0: Validación de variables
    - name: Validar variables requeridas
      debug:
        msg: "Validando variables para el host: {{ target_host }}"
      tags:
        - always

    - name: Establecer variables por defecto si no están definidas
      set_fact:
        server_root: "{{ server_root | default('/opt/www/sites') }}"
        ftp_user: "{{ ftp_user | default('ftpuser') }}"
        ssl_cert_dir: "{{ ssl_cert_dir | default('/etc/vsftpd') }}"
      tags:
        - always

    # Fase 1: Diagnóstico detallado
    - name: Verificar si VSFTPD está instalado
      command: which vsftpd
      register: vsftpd_installed
      ignore_errors: yes
      changed_when: false
      tags:
        - diagnose

    - name: Obtener estado detallado del servicio VSFTPD
      shell: systemctl status vsftpd || true
      register: vsftpd_status_detail
      changed_when: false
      ignore_errors: yes
      tags:
        - diagnose

    - name: Mostrar estado detallado del servicio
      debug:
        msg: "{{ vsftpd_status_detail.stdout_lines }}"
      tags:
        - diagnose

    - name: Verificar logs del sistema para errores de VSFTPD
      shell: journalctl -u vsftpd --no-pager -n 20 || true
      register: vsftpd_logs
      changed_when: false
      ignore_errors: yes
      tags:
        - diagnose

    - name: Mostrar logs de VSFTPD
      debug:
        msg: "{{ vsftpd_logs.stdout_lines }}"
      tags:
        - diagnose

    # Fase 2: Detener el servicio VSFTPD
    - name: Detener servicio VSFTPD
      service:
        name: vsftpd
        state: stopped
      ignore_errors: yes
      tags:
        - service

    # Fase 3: Corregir configuración de VSFTPD
    - name: Hacer backup del archivo vsftpd.conf
      copy:
        src: /etc/vsftpd/vsftpd.conf
        dest: /etc/vsftpd/vsftpd.conf.bak.{{ ansible_date_time.date }}_{{ ansible_date_time.time | regex_replace(':', '') }}
        remote_src: yes
      ignore_errors: yes
      tags:
        - configure

    - name: Crear una configuración VSFTPD simplificada
      copy:
        content: |
          # Configuración básica de VSFTPD generada por Fix-VSFTPD-SSL-Config-v2.yml
          # Configuración básica
          listen=YES
          listen_port={{ ftp_port | default(21) }}
          anonymous_enable=NO
          local_enable=YES
          write_enable=YES
          local_umask=022
          dirmessage_enable=YES
          use_localtime=YES
          xferlog_enable=YES
          connect_from_port_20=YES
          xferlog_std_format=YES
          chroot_local_user=YES
          allow_writeable_chroot=YES
          hide_ids=YES
          
          # Configuración de puertos pasivos
          pasv_enable=YES
          pasv_min_port={{ pasv_min_port | default(30000) }}
          pasv_max_port={{ pasv_max_port | default(31000) }}
          
          # Configuración de seguridad - SSL desactivado inicialmente
          ssl_enable=NO
          
          # Configuración de usuarios
          userlist_enable=YES
          userlist_deny=NO
          userlist_file=/etc/vsftpd/vsftpd.users
          
          # Configuración de logs
          dual_log_enable=YES
          log_ftp_protocol=YES
          vsftpd_log_file=/var/log/vsftpd.log
          
          # Configuración de timeout
          idle_session_timeout=600
          data_connection_timeout=120
          
          # Configuración de banner
          ftpd_banner=Bienvenido al servidor FTP de {{ target_host }}
        dest: /etc/vsftpd/vsftpd.conf
        mode: '0600'
      tags:
        - configure

    # Fase 4: Reiniciar VSFTPD sin SSL inicialmente
    - name: Reiniciar VSFTPD con configuración básica (sin SSL)
      service:
        name: vsftpd
        state: restarted
        enabled: yes
      register: restart_result
      ignore_errors: yes
      tags:
        - service

    - name: Verificar si el reinicio sin SSL fue exitoso
      debug:
        msg: "{{ 'Reinicio exitoso sin SSL' if restart_result.failed == false else 'Reinicio fallido incluso sin SSL' }}"
      tags:
        - service

    # Fase 5: Verificar estado del servicio
    - name: Obtener estado actualizado del servicio VSFTPD
      shell: systemctl status vsftpd || true
      register: vsftpd_status_updated
      changed_when: false
      ignore_errors: yes
      tags:
        - diagnose

    - name: Mostrar estado actualizado del servicio
      debug:
        msg: "{{ vsftpd_status_updated.stdout_lines }}"
      tags:
        - diagnose

    # Fase 6: Resumen y recomendaciones
    - name: Mensaje de diagnóstico y recomendaciones
      debug:
        msg: |
          Diagnóstico de VSFTPD completado:
          - Host: {{ target_host }}
          - Estado del servicio: {{ 'Activo' if restart_result.failed == false else 'Inactivo' }}
          
          Recomendaciones:
          1. El servicio VSFTPD ha sido configurado temporalmente sin SSL para facilitar la solución de problemas.
          2. Pruebe conectarse al servidor FTP sin SSL para verificar que el servicio funciona correctamente.
          3. Una vez confirmado que funciona, puede habilitar SSL modificando el archivo /etc/vsftpd/vsftpd.conf.
          
          Para probar la conexión FTP:
          - Servidor: {{ target_host }}
          - Puerto: {{ ftp_port | default(21) }}
          - Usuario: {{ ftp_user }}
          - Directorio: {{ server_root }}/{{ target_host }}
          
          Para habilitar SSL manualmente:
          1. Edite el archivo /etc/vsftpd/vsftpd.conf
          2. Cambie ssl_enable=NO a ssl_enable=YES
          3. Agregue las siguientes líneas:
             rsa_cert_file=/etc/vsftpd/vsftpd.pem
             rsa_private_key_file=/etc/vsftpd/vsftpd.pem
          4. Reinicie el servicio: systemctl restart vsftpd
      tags:
        - always
