- name: Instalar paquete b치sico
  hosts: target_host
  become: true
  tasks:
    - name: Instalar paquete vim (DNF)
      ansible.builtin.yum:
        name: vim-enhanced
        state: present
      when: ansible_os_family == "RedHat"
      register: dnf_result

    - name: Verificar versi칩n de vim instalada
      ansible.builtin.command: vim --version
      register: vim_version
      changed_when: false

    - debug:
        var: vim_version.stdout_lines

    - name: Verificar que vim est치 instalado
      ansible.builtin.command: which vim
      register: vim_check
      changed_when: false
      failed_when: vim_check.rc != 0

    - name: Mostrar resultado de verificaci칩n
      debug:
        var: vim_check