---
- name: Instalación y configuración de Pure-FTPd para hosts
  hosts: target_host
  become: yes
  tasks:
    # Fase 0: Validación de variables
    - name: Validar variables requeridas
      debug:
        msg: "Validando variables para el host: {{ target_host }}"
      tags:
        - always

    - name: Establecer variables por defecto si no están definidas
      set_fact:
        server_root: "{{ server_root | default('/opt/www/sites') }}"
        ftp_user: "{{ ftp_user | default('ftpuser') }}"
        ftp_password: "{{ ftp_password | default('changeme') }}"
        ftp_port: "{{ ftp_port | default(21) }}"
        pasv_min_port: "{{ pasv_min_port | default(30000) }}"
        pasv_max_port: "{{ pasv_max_port | default(31000) }}"
        apache_group: "{{ apache_group | default('apache') }}"
      tags:
        - always

    # Fase 1: Verificación previa y diagnóstico
    - name: Verificar si Apache está instalado
      command: which httpd
      register: httpd_installed
      ignore_errors: yes
      changed_when: false
      tags:
        - diagnose

    - name: Mostrar advertencia si Apache no está instalado
      debug:
        msg: "ADVERTENCIA: Apache no está instalado. Se recomienda instalar Apache primero usando el playbook Install HTTPD Host (Optimized v2)."
      when: httpd_installed.rc != 0
      tags:
        - diagnose

    - name: Verificar si Pure-FTPd está instalado
      command: which pure-ftpd
      register: pureftpd_installed
      ignore_errors: yes
      changed_when: false
      tags:
        - diagnose

    # Fase 2: Actualización e instalación
    - name: Actualizar sistema operativo
      dnf:
        name: '*'
        state: latest
        update_cache: yes
      register: result_update
      ignore_errors: yes
      tags:
        - install

    - name: Instalar Pure-FTPd
      dnf:
        name: pure-ftpd
        state: present
      register: pureftpd_install
      tags:
        - install

    # Fase 3: Configuración de firewall
    - name: Asegurar que el servicio firewalld esté iniciado y habilitado
      service:
        name: firewalld
        state: started
        enabled: yes
      ignore_errors: yes
      tags:
        - firewall

    - name: Abrir puerto FTP permanentemente en el firewall
      shell: firewall-cmd --permanent --add-port={{ ftp_port }}/tcp
      ignore_errors: yes
      tags:
        - firewall

    - name: Abrir puertos pasivos FTP en el firewall
      shell: firewall-cmd --permanent --add-port={{ pasv_min_port }}-{{ pasv_max_port }}/tcp
      ignore_errors: yes
      tags:
        - firewall

    - name: Recargar firewalld
      shell: firewall-cmd --reload
      ignore_errors: yes
      tags:
        - firewall

    # Fase 4: Configuración de SELinux
    - name: Configurar SELinux para permitir FTP
      shell: |
        setsebool -P ftpd_full_access on
        chcon -R -t public_content_rw_t {{ server_root }}/{{ target_host }}
      ignore_errors: yes
      tags:
        - selinux

    # Fase 5: Crear grupo y usuario FTP
    - name: Crear grupo FTP
      group:
        name: ftpgroup
        state: present
      tags:
        - user

    - name: Verificar si el usuario FTP existe
      getent:
        database: passwd
        key: "{{ ftp_user }}"
      register: ftp_user_exists
      ignore_errors: yes
      tags:
        - user

    - name: Crear usuario FTP si no existe
      user:
        name: "{{ ftp_user }}"
        password: "{{ ftp_password | password_hash('sha512') }}"
        group: ftpgroup
        groups: "{{ apache_group }}"
        append: yes
        shell: /sbin/nologin
        home: "{{ server_root }}/{{ target_host }}"
        create_home: no
      when: ftp_user_exists.failed is defined and ftp_user_exists.failed
      tags:
        - user

    - name: Asegurar que /sbin/nologin está en /etc/shells
      lineinfile:
        path: /etc/shells
        line: /sbin/nologin
        state: present
      tags:
        - user

    # Fase 6: Crear directorios necesarios
    - name: Verificar directorio del usuario FTP
      stat:
        path: "{{ server_root }}/{{ target_host }}"
      register: ftp_dir_stat
      tags:
        - directories

    - name: Crear directorio para el usuario FTP si no existe
      file:
        path: "{{ server_root }}/{{ target_host }}"
        state: directory
        owner: "{{ ftp_user }}"
        group: ftpgroup
        mode: '0750'
      when: not ftp_dir_stat.stat.exists
      tags:
        - directories

    # Fase 7: Configurar Pure-FTPd
    - name: Crear directorio de configuración si no existe
      file:
        path: /etc/pure-ftpd
        state: directory
        mode: '0755'
      tags:
        - configure

    - name: Configurar Pure-FTPd
      copy:
        content: |
          # Configuración de Pure-FTPd generada por Install-PureFTPD-Optimized-v1.yml
          PureDB                        /etc/pure-ftpd/pureftpd.pdb
          CreateHomeDir                 yes
          UnixAuthentication            yes
          PassivePortRange              {{ pasv_min_port }} {{ pasv_max_port }}
          
          # Configuración de seguridad
          ChrootEveryone                yes
          NoAnonymous                   yes
          AnonymousOnly                 no
          PAMAuthentication             yes
          
          # Configuración de logs
          Daemonize                     yes
          VerboseLog                    yes
          
          # Configuración de conexiones
          MaxClientsNumber              50
          MaxClientsPerIP               8
          
          # Configuración de tiempos
          MaxIdleTime                   15
          
          # Configuración de mensajes
          FortunesFile                  /etc/pure-ftpd/welcome.msg
        dest: /etc/pure-ftpd/pure-ftpd.conf
        mode: '0644'
      tags:
        - configure

    - name: Crear mensaje de bienvenida
      copy:
        content: "Bienvenido al servidor FTP de {{ target_host }}\n"
        dest: /etc/pure-ftpd/welcome.msg
        mode: '0644'
      tags:
        - configure

    # Fase 8: Crear usuario virtual
    - name: Crear usuario virtual FTP
      shell: |
        pure-pw useradd "{{ ftp_user }}" -u "{{ ftp_user }}" -g ftpgroup -d "{{ server_root }}/{{ target_host }}" -m <<< "{{ ftp_password }}"
        pure-pw mkdb
      args:
        executable: /bin/bash
      ignore_errors: yes
      tags:
        - configure

    # Fase 9: Crear enlaces simbólicos necesarios
    - name: Crear directorio de autenticación si no existe
      file:
        path: /etc/pure-ftpd/auth
        state: directory
        mode: '0755'
      tags:
        - configure

    - name: Crear directorio de configuración si no existe
      file:
        path: /etc/pure-ftpd/conf
        state: directory
        mode: '0755'
      tags:
        - configure

    - name: Crear archivo PureDB en conf
      copy:
        content: "/etc/pure-ftpd/pureftpd.pdb"
        dest: /etc/pure-ftpd/conf/PureDB
        mode: '0644'
      tags:
        - configure

    - name: Crear enlaces simbólicos
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
        force: yes
      with_items:
        - { src: "/etc/pure-ftpd/pureftpd.pdb", dest: "/etc/pureftpd.pdb" }
        - { src: "/etc/pure-ftpd/conf/PureDB", dest: "/etc/pure-ftpd/auth/PureDB" }
      tags:
        - configure

    # Fase 10: Establecer permisos
    - name: Establecer permisos recursivos en el directorio del sitio
      shell: |
        chown -R {{ ftp_user }}:ftpgroup {{ server_root }}/{{ target_host }}
        chmod 750 {{ server_root }}/{{ target_host }}
      ignore_errors: yes
      tags:
        - permissions

    # Fase 11: Verificar y reiniciar Pure-FTPd
    - name: Habilitar e iniciar servicio Pure-FTPd
      service:
        name: pure-ftpd
        state: restarted
        enabled: yes
      register: pureftpd_service
      tags:
        - service

    - name: Verificar estado del servicio Pure-FTPd
      command: systemctl status pure-ftpd
      register: pureftpd_status
      ignore_errors: yes
      changed_when: false
      tags:
        - service

    - name: Mostrar estado del servicio
      debug:
        msg: "{{ pureftpd_status.stdout_lines }}"
      tags:
        - service

    # Fase 12: Actualizar index.html
    - name: Verificar si existe index.html
      stat:
        path: "{{ server_root }}/{{ target_host }}/index.html"
      register: index_exists
      tags:
        - index

    - name: Actualizar index.html con información de FTP
      block:
        - name: Leer contenido del archivo index.html
          slurp:
            src: "{{ server_root }}/{{ target_host }}/index.html"
          register: index_content
          when: index_exists.stat.exists
          
        - name: Decodificar contenido
          set_fact:
            decoded_content: "{{ index_content['content'] | b64decode }}"
          when: index_exists.stat.exists
          
        - name: Verificar si ya existe badge de FTP
          set_fact:
            has_ftp_badge: "{{ decoded_content | regex_search('FTP Status') != None }}"
          when: index_exists.stat.exists
          
        - name: Añadir badge de FTP si no existe
          replace:
            path: "{{ server_root }}/{{ target_host }}/index.html"
            regexp: '(<div class="container mt-5">.*?<h1>)'
            replace: '\1<div class="alert alert-success mb-4"><strong>FTP Status:</strong> Pure-FTPd Configured and Running ({{ ansible_date_time.date }})</div>'
          when: index_exists.stat.exists and (has_ftp_badge is not defined or not has_ftp_badge)
          
        - name: Actualizar badge de FTP si ya existe
          replace:
            path: "{{ server_root }}/{{ target_host }}/index.html"
            regexp: '<div class="alert alert-(success|warning|danger) mb-4"><strong>FTP Status:</strong>.*?</div>'
            replace: '<div class="alert alert-success mb-4"><strong>FTP Status:</strong> Pure-FTPd Configured and Running ({{ ansible_date_time.date }})</div>'
          when: index_exists.stat.exists and has_ftp_badge is defined and has_ftp_badge
      when: index_exists.stat.exists and pureftpd_service.failed is not defined
      ignore_errors: yes
      tags:
        - index

    # Fase 13: Resumen y recomendaciones
    - name: Mensaje de diagnóstico y recomendaciones
      debug:
        msg: |
          Instalación de Pure-FTPd completada:
          - Host: {{ target_host }}
          - Estado del servicio: {{ 'Activo' if pureftpd_service.failed is not defined else 'Inactivo' }}
          - Directorio FTP: {{ server_root }}/{{ target_host }}
          - Usuario FTP: {{ ftp_user }}
          - Contraseña: {{ ftp_password }}
          - Puerto: {{ ftp_port }}
          - Rango de puertos pasivos: {{ pasv_min_port }}-{{ pasv_max_port }}
          
          Para probar la conexión FTP:
          - Servidor: {{ target_host }}
          - Puerto: {{ ftp_port }}
          - Usuario: {{ ftp_user }}
          - Contraseña: {{ ftp_password }}
          
          Ventajas de Pure-FTPd:
          1. Configuración sencilla y robusta
          2. Excelente rendimiento y estabilidad
          3. Soporte para usuarios virtuales
          4. Buena integración con SELinux
          5. Menor huella de memoria que otras alternativas
      tags:
        - always
