- name: Instalar nano en RedHat/Oracle Linux
  hosts: target_host
  become: true
  tasks:
    - name: Instalar nano (DNF)
      ansible.builtin.yum:
        name: nano
        state: present
      when: ansible_os_family == "RedHat"
      register: nano_result

    - name: Verificar versión de nano instalada
      ansible.builtin.command: nano --version
      register: nano_version
      changed_when: false

    - debug:
        var: nano_version.stdout_lines

    - name: Verificar que nano está instalado
      ansible.builtin.command: which nano
      register: nano_check
      changed_when: false
      failed_when: nano_check.rc != 0

    - name: Mostrar resultado de verificación
      debug:
        var: nano_check