---
- name: Instalar epel-release en todos los hosts de un grupo
  hosts: target_group
  become: true
  tasks:
    - name: Instalar epel-release (DNF)
      ansible.builtin.yum:
        name: epel-release
        state: present
      when: ansible_os_family == "RedHat"