# Generated by Django 5.0.14 on 2025-05-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_group_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ansible_python_interpreter',
            field=models.CharField(default='/usr/bin/python3.12', max_length=255),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='host',
            name='operating_system',
            field=models.CharField(choices=[('Windows', 'Windows'), ('RedHat', 'RedHat'), ('Debian', 'Debian')], max_length=50),
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='host',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
