# Generated by Django 5.0.14 on 2025-05-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_host_ansible_python_interpreter_alter_host_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='ansible_become',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='host',
            name='ansible_become_method',
            field=models.CharField(default='sudo', max_length=50),
        ),
        migrations.AddField(
            model_name='host',
            name='ansible_become_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='ansible_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='ansible_python_interpreter',
            field=models.CharField(default='/usr/bin/python3.9', max_length=255),
        ),
    ]
