# Generated by Django 5.0.14 on 2025-05-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_host_ansible_become_host_ansible_become_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='ansible_ssh_private_key_file',
            field=models.CharField(blank=True, help_text='Ruta al archivo de llave privada SSH (ej: /home/usuario/.ssh/id_rsa)', max_length=255, null=True),
        ),
    ]
