# Generated by Django 5.0.14 on 2025-05-11 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_remove_deploymentcredential_email_and_more'),
        ('inventory', '0005_host_ansible_ssh_private_key_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='ansible_become_password',
        ),
        migrations.RemoveField(
            model_name='host',
            name='ansible_ssh_private_key_file',
        ),
        migrations.AddField(
            model_name='host',
            name='deployment_credential',
            field=models.ForeignKey(blank=True, help_text='Deployment credential from settings', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_settings.deploymentcredential'),
        ),
    ]
