# Generated by Django 4.2.21 on 2025-05-14 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_host_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='port',
        ),
    ]
