# Generated by Django 5.0.14 on 2025-05-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_host_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='ansible_connection',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='ansible_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='ansible_winrm_scheme',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='ansible_winrm_server_cert_validation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
