# Generated by Django 5.0.14 on 2025-05-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_host_ansible_connection_host_ansible_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='ansible_shell_type',
            field=models.CharField(blank=True, help_text='Tipo de shell a usar (ej: powershell, cmd, bash)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='ansible_ssh_common_args',
            field=models.TextField(blank=True, help_text='Argumentos adicionales para SSH', null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='ansible_ssh_private_key_file',
            field=models.CharField(blank=True, help_text='Ruta al archivo de llave privada SSH', max_length=255, null=True),
        ),
    ]
