# Generated by Django 4.2.21 on 2025-05-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='execution_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('sequential', 'Sequential'), ('scheduled', 'Scheduled')], default='manual', max_length=12),
        ),
    ]
