# Generated by Django 4.2.21 on 2025-05-18 10:58

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_history_execution_type'),
        ('inventory', '0001_initial'),  # Asegúrate de que inventory esté en las dependencias
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.environment'),
            preserve_default=False,
        ),
    ]
