# Generated by Django 5.0.14 on 2025-05-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('operating_system', models.CharField(choices=[('Windows', 'Windows'), ('RedHat', 'RedHat'), ('Debian', 'Debian')], max_length=10)),
                ('file', models.FileField(upload_to='yml/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
