# Generated by Django 5.0.14 on 2025-05-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploymentcredential',
            name='email',
        ),
        migrations.AlterField(
            model_name='deploymentcredential',
            name='ssh_private_key_file',
            field=models.CharField(help_text='Path to the SSH private key file', max_length=255),
        ),
    ]
