# Generated by Django 5.0.14 on 2025-05-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_remove_deploymentcredential_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploymentcredential',
            name='ssh_private_key_file',
        ),
        migrations.AddField(
            model_name='deploymentcredential',
            name='ssh_private_key_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
