# Generated by Django 5.0.14 on 2025-05-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0003_remove_deploymentcredential_ssh_private_key_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentcredential',
            name='windows_password_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
