# Generated by Django 4.2.21 on 2025-05-15 00:37

import app_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0004_deploymentcredential_windows_password_encrypted'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSLCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo para el certificado', max_length=100)),
                ('certificate_type', models.CharField(choices=[('cert', 'Certificado (certificado.crt)'), ('key', 'Clave Privada (certificado.key)'), ('provider', 'Certificado Proveedor (certificado-provider.crt)')], max_length=20)),
                ('file', models.FileField(upload_to='templates/ssl/', validators=[app_settings.models.validate_file_extension])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('name', 'certificate_type')},
            },
        ),
    ]
