# Generated by Django 5.0.14 on 2025-05-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0005_sslcertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslcertificate',
            name='certificate_type',
            field=models.CharField(choices=[('cert', 'Certificate'), ('key', 'Private Key'), ('provider', 'Provider Certificate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sslcertificate',
            name='name',
            field=models.CharField(help_text='Descriptive name for the certificate', max_length=100),
        ),
    ]
